<?php
                
namespace App\Lang\Customers;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LForm {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function companyInformations() {
        return trans('customers/form.company_informations');
    } 
                                                
    public static function uniqueLabel() {
        return trans('customers/form.unique_label');
    } 
                                                
    public static function firstName() {
        return trans('customers/form.first_name');
    } 
                                                
    public static function lastName() {
        return trans('customers/form.last_name');
    } 
                                                
    public static function companyName() {
        return trans('customers/form.company_name');
    } 
                                                
    public static function address() {
        return trans('customers/form.address');
    } 
                                                
    public static function postal() {
        return trans('customers/form.postal');
    } 
                                                
    public static function city() {
        return trans('customers/form.city');
    } 
                                                
    public static function province() {
        return trans('customers/form.province');
    } 
                                                
    public static function country() {
        return trans('customers/form.country');
    } 
                                                
    public static function vat() {
        return trans('customers/form.vat');
    } 
                                                
    public static function fiscalCode() {
        return trans('customers/form.fiscal_code');
    } 
                                                
    public static function phone() {
        return trans('customers/form.phone');
    } 
                                                
    public static function email() {
        return trans('customers/form.email');
    } 
                                                
    public static function webSite() {
        return trans('customers/form.web_site');
    } 
                                                
    public static function notes() {
        return trans('customers/form.notes');
    } 
                                                
    public static function active_label() {
        return trans('customers/form.active.label');
    } 
                                                
    public static function active_values_0() {
        return trans('customers/form.active.values.0');
    } 
                                                
    public static function active_values_1() {
        return trans('customers/form.active.values.1');
    } 
                                        
    public static function active_values() {
        return self::__values('customers/form.active.values',func_get_args());
    }
                                
    public static function createdAt() {
        return trans('customers/form.created_at');
    } 
                                                
    public static function deletedAt() {
        return trans('customers/form.deleted_at');
    } 
                                                
    public static function actions() {
        return trans('customers/form.actions');
    } 
                                                
    public static function playerCount() {
        return trans('customers/form.player_count');
    } 
                                                
    public static function uniqueLabel_placeholder() {
        return trans('customers/form.unique_label.placeholder');
    } 
                                                
    public static function securityToken() {
        return trans('customers/form.security_token');
    } 
                                                
    public static function owner() {
        return trans('customers/form.owner');
    } 
                                                
    public static function manager() {
        return trans('customers/form.manager');
    } 
                                                
    public static function location() {
        return trans('customers/form.location');
    } 
                                                
    public static function playersTooltip() {
        return trans('customers/form.players_tooltip');
    } 
                                                
    public static function createPlayerTooltip() {
        return trans('customers/form.create_player_tooltip');
    } 
                                                
    public static function firstName_placeholder() {
        return trans('form.first_name.placeholder');
    } 
                                                
    public static function lastName_placeholder() {
        return trans('form.last_name.placeholder');
    } 
                                                
    public static function password_placeholder() {
        return trans('form.password.placeholder');
    } 
                                                
    public static function passwordConfirm_placeholder() {
        return trans('form.password_confirm.placeholder');
    } 
                                                
    public static function companyName_placeholder() {
        return trans('form.company_name.placeholder');
    } 
                                                
    public static function address_placeholder() {
        return trans('form.address.placeholder');
    } 
                                                
    public static function postal_placeholder() {
        return trans('form.postal.placeholder');
    } 
                                                
    public static function city_placeholder() {
        return trans('form.city.placeholder');
    } 
                                                
    public static function province_placeholder() {
        return trans('form.province.placeholder');
    } 
                                                
    public static function country_placeholder() {
        return trans('form.country.placeholder');
    } 
                                                
    public static function fiscalCode_placeholder() {
        return trans('form.fiscal_code.placeholder');
    } 
                                                
    public static function vat_placeholder() {
        return trans('form.vat.placeholder');
    } 
                                                
    public static function dob_placeholder() {
        return trans('form.dob.placeholder');
    } 
                                                
    public static function phone_placeholder() {
        return trans('form.phone.placeholder');
    } 
                                                
    public static function webSite_placeholder() {
        return trans('form.web_site.placeholder');
    } 
                                                
    public static function email_placeholder() {
        return trans('form.email.placeholder');
    } 
                                                
    public static function notes_placeholder() {
        return trans('form.notes.placeholder');
    } 
                                                
    public static function editTooltip() {
        return trans('form.edit_tooltip');
    } 
                                                
    public static function deleteTooltip() {
        return trans('form.delete_tooltip');
    } 
                                                
    public static function showTooltip() {
        return trans('form.show_tooltip');
    } 
                                                
    public static function restoreTooltip() {
        return trans('form.restore_tooltip');
    } 
                                                
    public static function apiPassword_placeholder() {
        return trans('form.api_password.placeholder');
    } 
                                                
    public static function daytime_placeholder() {
        return trans('form.daytime.placeholder');
    } 
                                                
    public static function minutes_placeholder() {
        return trans('form.minutes.placeholder');
    } 
                                                
    public static function note() {
        return trans('form.note');
    } 
                                                
    public static function note_placeholder() {
        return trans('form.note.placeholder');
    } 
                                                
    public static function select_timeZone() {
        return trans('form.select.time_zone');
    } 
                                                
    public static function select_country() {
        return trans('form.select.country');
    } 
                                
}
