<?php
                
namespace App\Lang\Players;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LForm {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function id() {
        return trans('players/form.id');
    } 
                                                
    public static function uniqueLabel() {
        return trans('players/form.unique_label');
    } 
                                                
    public static function status_requested() {
        return trans('players/form.status.requested');
    } 
                                                
    public static function status_shipped() {
        return trans('players/form.status.shipped');
    } 
                                                
    public static function status_received() {
        return trans('players/form.status.received');
    } 
                                                
    public static function status_active() {
        return trans('players/form.status.active');
    } 
                                                
    public static function status_limited() {
        return trans('players/form.status.limited');
    } 
                                                
    public static function status_blocked() {
        return trans('players/form.status.blocked');
    } 
                                                
    public static function status_returned() {
        return trans('players/form.status.returned');
    } 
                                                
    public static function rsyncPassword() {
        return trans('players/form.rsync_password');
    } 
                                                
    public static function address() {
        return trans('players/form.address');
    } 
                                                
    public static function postal() {
        return trans('players/form.postal');
    } 
                                                
    public static function city() {
        return trans('players/form.city');
    } 
                                                
    public static function province() {
        return trans('players/form.province');
    } 
                                                
    public static function state() {
        return trans('players/form.state');
    } 
                                                
    public static function timeZone() {
        return trans('players/form.time_zone');
    } 
                                                
    public static function playStartTime() {
        return trans('players/form.play_start_time');
    } 
                                                
    public static function playEndTime() {
        return trans('players/form.play_end_time');
    } 
                                                
    public static function playEndTimeDayOffset() {
        return trans('players/form.play_end_time_day_offset');
    } 
                                                
    public static function checkPlayMinutesInterval() {
        return trans('players/form.check_play_minutes_interval');
    } 
                                                
    public static function filesUpdateTime() {
        return trans('players/form.files_update_time');
    } 
                                                
    public static function createdAt() {
        return trans('players/form.created_at');
    } 
                                                
    public static function actions() {
        return trans('players/form.actions');
    } 
                                                
    public static function customerUniqueLabel() {
        return trans('players/form.customer_unique_label');
    } 
                                                
    public static function uniqueLabel_placeholder() {
        return trans('players/form.unique_label.placeholder');
    } 
                                                
    public static function registrationCode() {
        return trans('players/form.registration_code');
    } 
                                                
    public static function registrationCode_placeholder() {
        return trans('players/form.registration_code.placeholder');
    } 
                                                
    public static function status_label() {
        return trans('players/form.status.label');
    } 
                                                
    public static function status_values_UNREGISTERED() {
        return trans('players/form.status.values.UNREGISTERED');
    } 
                                                
    public static function status_values_REGISTERED() {
        return trans('players/form.status.values.REGISTERED');
    } 
                                                
    public static function status_values_ACTIVE() {
        return trans('players/form.status.values.ACTIVE');
    } 
                                                
    public static function status_values_LIMITED() {
        return trans('players/form.status.values.LIMITED');
    } 
                                                
    public static function status_values_BLOCKED() {
        return trans('players/form.status.values.BLOCKED');
    } 
                                                
    public static function status_values_DELETED() {
        return trans('players/form.status.values.DELETED');
    } 
                                        
    public static function status_values() {
        return self::__values('players/form.status.values',func_get_args());
    }
                                
    public static function securityToken() {
        return trans('players/form.security_token');
    } 
                                                
    public static function playlistsDj() {
        return trans('players/form.playlists_dj');
    } 
                                                
    public static function playlistsDj_placeholder() {
        return trans('players/form.playlists_dj.placeholder');
    } 
                                                
    public static function apiPassword() {
        return trans('players/form.api_password');
    } 
                                                
    public static function location() {
        return trans('players/form.location');
    } 
                                                
    public static function country() {
        return trans('players/form.country');
    } 
                                                
    public static function playEndTimeDayOffset_label() {
        return trans('players/form.play_end_time_day_offset.label');
    } 
                                                
    public static function playEndTimeDayOffset_values_0() {
        return trans('players/form.play_end_time_day_offset.values.0');
    } 
                                                
    public static function playEndTimeDayOffset_values_1() {
        return trans('players/form.play_end_time_day_offset.values.1');
    } 
                                        
    public static function playEndTimeDayOffset_values() {
        return self::__values('players/form.play_end_time_day_offset.values',func_get_args());
    }
                                
    public static function loopPlaylist_label() {
        return trans('players/form.loop_playlist.label');
    } 
                                                
    public static function loopPlaylist_values_0() {
        return trans('players/form.loop_playlist.values.0');
    } 
                                                
    public static function loopPlaylist_values_1() {
        return trans('players/form.loop_playlist.values.1');
    } 
                                        
    public static function loopPlaylist_values() {
        return self::__values('players/form.loop_playlist.values',func_get_args());
    }
                                
    public static function startFromBeginning_label() {
        return trans('players/form.start_from_beginning.label');
    } 
                                                
    public static function startFromBeginning_values_0() {
        return trans('players/form.start_from_beginning.values.0');
    } 
                                                
    public static function startFromBeginning_values_1() {
        return trans('players/form.start_from_beginning.values.1');
    } 
                                        
    public static function startFromBeginning_values() {
        return self::__values('players/form.start_from_beginning.values',func_get_args());
    }
                                
    public static function active_label() {
        return trans('players/form.active.label');
    } 
                                                
    public static function active_values_0() {
        return trans('players/form.active.values.0');
    } 
                                                
    public static function active_values_1() {
        return trans('players/form.active.values.1');
    } 
                                        
    public static function active_values() {
        return self::__values('players/form.active.values',func_get_args());
    }
                                
    public static function playlists_tooltip() {
        return trans('players/form.playlists.tooltip');
    } 
                                                
    public static function spots_tooltip() {
        return trans('players/form.spots.tooltip');
    } 
                                                
    public static function playerNotifications_tooltip() {
        return trans('players/form.player_notifications.tooltip');
    } 
                                                
    public static function createPlaylist_tooltip() {
        return trans('players/form.create_playlist.tooltip');
    } 
                                                
    public static function generateUpdatePackage_tooltip() {
        return trans('players/form.generate_update_package.tooltip');
    } 
                                                
    public static function firstName_placeholder() {
        return trans('form.first_name.placeholder');
    } 
                                                
    public static function lastName_placeholder() {
        return trans('form.last_name.placeholder');
    } 
                                                
    public static function password_placeholder() {
        return trans('form.password.placeholder');
    } 
                                                
    public static function passwordConfirm_placeholder() {
        return trans('form.password_confirm.placeholder');
    } 
                                                
    public static function companyName_placeholder() {
        return trans('form.company_name.placeholder');
    } 
                                                
    public static function address_placeholder() {
        return trans('form.address.placeholder');
    } 
                                                
    public static function postal_placeholder() {
        return trans('form.postal.placeholder');
    } 
                                                
    public static function city_placeholder() {
        return trans('form.city.placeholder');
    } 
                                                
    public static function province_placeholder() {
        return trans('form.province.placeholder');
    } 
                                                
    public static function country_placeholder() {
        return trans('form.country.placeholder');
    } 
                                                
    public static function fiscalCode_placeholder() {
        return trans('form.fiscal_code.placeholder');
    } 
                                                
    public static function vat_placeholder() {
        return trans('form.vat.placeholder');
    } 
                                                
    public static function dob_placeholder() {
        return trans('form.dob.placeholder');
    } 
                                                
    public static function phone_placeholder() {
        return trans('form.phone.placeholder');
    } 
                                                
    public static function webSite_placeholder() {
        return trans('form.web_site.placeholder');
    } 
                                                
    public static function email_placeholder() {
        return trans('form.email.placeholder');
    } 
                                                
    public static function notes_placeholder() {
        return trans('form.notes.placeholder');
    } 
                                                
    public static function editTooltip() {
        return trans('form.edit_tooltip');
    } 
                                                
    public static function deleteTooltip() {
        return trans('form.delete_tooltip');
    } 
                                                
    public static function showTooltip() {
        return trans('form.show_tooltip');
    } 
                                                
    public static function restoreTooltip() {
        return trans('form.restore_tooltip');
    } 
                                                
    public static function apiPassword_placeholder() {
        return trans('form.api_password.placeholder');
    } 
                                                
    public static function daytime_placeholder() {
        return trans('form.daytime.placeholder');
    } 
                                                
    public static function minutes_placeholder() {
        return trans('form.minutes.placeholder');
    } 
                                                
    public static function note() {
        return trans('form.note');
    } 
                                                
    public static function note_placeholder() {
        return trans('form.note.placeholder');
    } 
                                                
    public static function select_timeZone() {
        return trans('form.select.time_zone');
    } 
                                                
    public static function select_country() {
        return trans('form.select.country');
    } 
                                
}
