{{-- Menus generated by CRUD generator --}}

<li class="menu-dropdown {{ (Request::is('admin/boxed') || Request::is('admin/layout_fixed_header') || Request::is('admin/layout_boxed_fixed_header') || Request::is('admin/layout_fixed') ? 'active' : '') }}">
    <a href="#">
        <i class="menu-icon fa fa-th"></i>
        <span>Layouts</span>
        <span class="fa arrow"></span>
    </a>
    <ul class="sub-menu">
        <li {{ (Request::is('admin/boxed') ? 'class=active' : '') }}>
            <a href="{{ URL::to('admin/boxed') }}">
                <i class="fa fa-fw fa-th-large"></i>
                Boxed Layout
            </a>
        </li>
        <li {{ (Request::is('admin/layout_fixed_header') ? 'class=active' : '') }}>
            <a href="{{ URL::to('admin/layout_fixed_header') }}">
                <i class="fa fa-fw fa-th-list"></i>
                Fixed Header
            </a>
        </li>
        <li {{ (Request::is('admin/layout_boxed_fixed_header') ? 'class=active' : '') }}>
            <a href="{{ URL::to('admin/layout_boxed_fixed_header') }}">
                <i class="fa fa-fw fa-th"></i>
                Boxed &amp; Fixed Header
            </a>
        </li>
        <li {{ (Request::is('admin/layout_fixed') ? 'class=active' : '') }}>
            <a href="{{ URL::to('admin/layout_fixed') }}">
                <i class="fa fa-fw fa-indent"></i>
                Fixed Header &amp; Menu
            </a>
        </li>
    </ul>
</li>