<?php
                
namespace App\Lang\Playlists;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LForm {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function id() {
        return trans('playlists/form.id');
    } 
                                                
    public static function title() {
        return trans('playlists/form.title');
    } 
                                                
    public static function status_notActiveOld() {
        return trans('playlists/form.status.not_active_old');
    } 
                                                
    public static function status_notActive() {
        return trans('playlists/form.status.not_active');
    } 
                                                
    public static function status_workInProgress() {
        return trans('playlists/form.status.work_in_progress');
    } 
                                                
    public static function status_active() {
        return trans('playlists/form.status.active');
    } 
                                                
    public static function createdAt() {
        return trans('playlists/form.created_at');
    } 
                                                
    public static function actions() {
        return trans('playlists/form.actions');
    } 
                                                
    public static function customerLabelId() {
        return trans('playlists/form.customer_label_id');
    } 
                                                
    public static function playerLabelId() {
        return trans('playlists/form.player_label_id');
    } 
                                                
    public static function title_placeholder() {
        return trans('playlists/form.title.placeholder');
    } 
                                                
    public static function status_label() {
        return trans('playlists/form.status.label');
    } 
                                                
    public static function status_values_NOT_ACTIVE_OLD() {
        return trans('playlists/form.status.values.NOT_ACTIVE_OLD');
    } 
                                                
    public static function status_values_NOT_ACTIVE() {
        return trans('playlists/form.status.values.NOT_ACTIVE');
    } 
                                                
    public static function status_values_WORK_IN_PROGRESS() {
        return trans('playlists/form.status.values.WORK_IN_PROGRESS');
    } 
                                                
    public static function status_values_ACTIVE() {
        return trans('playlists/form.status.values.ACTIVE');
    } 
                                        
    public static function status_values() {
        return self::__values('playlists/form.status.values',func_get_args());
    }
                                
    public static function tracks() {
        return trans('playlists/form.tracks');
    } 
                                                
    public static function playlist() {
        return trans('playlists/form.playlist');
    } 
                                                
    public static function totalDuration() {
        return trans('playlists/form.total_duration');
    } 
                                                
    public static function order() {
        return trans('playlists/form.order');
    } 
                                                
    public static function trackType() {
        return trans('playlists/form.track_type');
    } 
                                                
    public static function trackName() {
        return trans('playlists/form.track_name');
    } 
                                                
    public static function album() {
        return trans('playlists/form.album');
    } 
                                                
    public static function artist() {
        return trans('playlists/form.artist');
    } 
                                                
    public static function duration() {
        return trans('playlists/form.duration');
    } 
                                                
    public static function noPlaylistElements() {
        return trans('playlists/form.no_playlist_elements');
    } 
                                                
    public static function activeNoStateEditingExplanation_title() {
        return trans('playlists/form.active_no_state_editing_explanation.title');
    } 
                                                
    public static function activeNoStateEditingExplanation_body() {
        return trans('playlists/form.active_no_state_editing_explanation.body');
    } 
                                                
    public static function firstName_placeholder() {
        return trans('form.first_name.placeholder');
    } 
                                                
    public static function lastName_placeholder() {
        return trans('form.last_name.placeholder');
    } 
                                                
    public static function password_placeholder() {
        return trans('form.password.placeholder');
    } 
                                                
    public static function passwordConfirm_placeholder() {
        return trans('form.password_confirm.placeholder');
    } 
                                                
    public static function companyName_placeholder() {
        return trans('form.company_name.placeholder');
    } 
                                                
    public static function address_placeholder() {
        return trans('form.address.placeholder');
    } 
                                                
    public static function postal_placeholder() {
        return trans('form.postal.placeholder');
    } 
                                                
    public static function city_placeholder() {
        return trans('form.city.placeholder');
    } 
                                                
    public static function province_placeholder() {
        return trans('form.province.placeholder');
    } 
                                                
    public static function country_placeholder() {
        return trans('form.country.placeholder');
    } 
                                                
    public static function fiscalCode_placeholder() {
        return trans('form.fiscal_code.placeholder');
    } 
                                                
    public static function vat_placeholder() {
        return trans('form.vat.placeholder');
    } 
                                                
    public static function dob_placeholder() {
        return trans('form.dob.placeholder');
    } 
                                                
    public static function phone_placeholder() {
        return trans('form.phone.placeholder');
    } 
                                                
    public static function webSite_placeholder() {
        return trans('form.web_site.placeholder');
    } 
                                                
    public static function email_placeholder() {
        return trans('form.email.placeholder');
    } 
                                                
    public static function notes_placeholder() {
        return trans('form.notes.placeholder');
    } 
                                                
    public static function editTooltip() {
        return trans('form.edit_tooltip');
    } 
                                                
    public static function deleteTooltip() {
        return trans('form.delete_tooltip');
    } 
                                                
    public static function showTooltip() {
        return trans('form.show_tooltip');
    } 
                                                
    public static function restoreTooltip() {
        return trans('form.restore_tooltip');
    } 
                                                
    public static function apiPassword_placeholder() {
        return trans('form.api_password.placeholder');
    } 
                                                
    public static function daytime_placeholder() {
        return trans('form.daytime.placeholder');
    } 
                                                
    public static function minutes_placeholder() {
        return trans('form.minutes.placeholder');
    } 
                                                
    public static function note() {
        return trans('form.note');
    } 
                                                
    public static function note_placeholder() {
        return trans('form.note.placeholder');
    } 
                                                
    public static function select_timeZone() {
        return trans('form.select.time_zone');
    } 
                                                
    public static function select_country() {
        return trans('form.select.country');
    } 
                                
}
