<?php
                
namespace App\Lang;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LButton {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function edit() {
        return trans('button.edit');
    } 
                                                
    public static function delete() {
        return trans('button.delete');
    } 
                                                
    public static function restore() {
        return trans('button.restore');
    } 
                                                
    public static function publish() {
        return trans('button.publish');
    } 
                                                
    public static function save() {
        return trans('button.save');
    } 
                                                
    public static function submit() {
        return trans('button.submit');
    } 
                                                
    public static function cancel() {
        return trans('button.cancel');
    } 
                                                
    public static function create() {
        return trans('button.create');
    } 
                                                
    public static function back() {
        return trans('button.back');
    } 
                                                
    public static function signin() {
        return trans('button.signin');
    } 
                                                
    public static function forgotpassword() {
        return trans('button.forgotpassword');
    } 
                                                
    public static function rememberme() {
        return trans('button.rememberme');
    } 
                                                
    public static function signup() {
        return trans('button.signup');
    } 
                                                
    public static function update() {
        return trans('button.update');
    } 
                                                
    public static function deleteAllReaded() {
        return trans('button.delete_all_readed');
    } 
                                
}
