<?php
                
namespace App\Lang;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LGeneral {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function admin_titleSuffix() {
        return trans('general.admin.title_suffix');
    } 
                                                
    public static function admin_login_title() {
        return trans('general.admin.login.title');
    } 
                                                
    public static function admin_login_rememberMe() {
        return trans('general.admin.login.remember_me');
    } 
                                                
    public static function admin_login_pageTitle() {
        return trans('general.admin.login.page_title');
    } 
                                                
    public static function mailAddress() {
        return trans('general.mail_address');
    } 
                                                
    public static function password() {
        return trans('general.password');
    } 
                                                
    public static function no() {
        return trans('general.no');
    } 
                                                
    public static function noresults() {
        return trans('general.noresults');
    } 
                                                
    public static function yes() {
        return trans('general.yes');
    } 
                                                
    public static function welcome() {
        return trans('general.welcome');
    } 
                                                
    public static function lock() {
        return trans('general.lock');
    } 
                                                
    public static function profile() {
        return trans('general.profile');
    } 
                                                
    public static function accountSettings() {
        return trans('general.account_settings');
    } 
                                                
    public static function login() {
        return trans('general.login');
    } 
                                                
    public static function logout() {
        return trans('general.logout');
    } 
                                                
    public static function admin_forgotPassword_title() {
        return trans('general.admin.forgot_password.title');
    } 
                                                
    public static function admin_login_forgotPassword() {
        return trans('general.admin.login.forgot_password');
    } 
                                                
    public static function admin_forgotPassword_pageTitle() {
        return trans('general.admin.forgot_password.page_title');
    } 
                                                
    public static function admin_logout() {
        return trans('general.admin.logout');
    } 
                                                
    public static function instructions() {
        return trans('general.instructions');
    } 
                                                
    public static function forgotPassword() {
        return trans('general.forgot_password');
    } 
                                                
    public static function unreadedNotifications_prefix() {
        return trans('general.unreaded_notifications.prefix');
    } 
                                                
    public static function unreadedNotifications_suffix() {
        return trans('general.unreaded_notifications.suffix');
    } 
                                
}
