<?php
                
namespace App\Lang;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LPagination {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function previous() {
        return trans('pagination.previous');
    } 
                                                
    public static function next() {
        return trans('pagination.next');
    } 
                                                
    public static function allEntitiesPrefix() {
        return trans('pagination.all_entities_prefix');
    } 
                                                
    public static function allEntitiesSuffix() {
        return trans('pagination.all_entities_suffix');
    } 
                                                
    public static function allWithDeletedPrefix() {
        return trans('pagination.all_with_deleted_prefix');
    } 
                                                
    public static function allWithDeletedSuffix() {
        return trans('pagination.all_with_deleted_suffix');
    } 
                                                
    public static function onlyDeletedPrefix() {
        return trans('pagination.only_deleted_prefix');
    } 
                                                
    public static function onlyDeletedSuffix() {
        return trans('pagination.only_deleted_suffix');
    } 
                                
}
