<?php
                
namespace App\Lang\Users;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LMessage {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function userExists() {
        return trans('users/message.user_exists');
    } 
                                                
    public static function userNotFound() {
        return trans('users/message.user_not_found');
    } 
                                                
    public static function userLoginRequired() {
        return trans('users/message.user_login_required');
    } 
                                                
    public static function userPasswordRequired() {
        return trans('users/message.user_password_required');
    } 
                                                
    public static function insufficientPermissions() {
        return trans('users/message.insufficient_permissions');
    } 
                                                
    public static function banned() {
        return trans('users/message.banned');
    } 
                                                
    public static function suspended() {
        return trans('users/message.suspended');
    } 
                                                
    public static function success_create() {
        return trans('users/message.success.create');
    } 
                                                
    public static function success_update() {
        return trans('users/message.success.update');
    } 
                                                
    public static function success_delete() {
        return trans('users/message.success.delete');
    } 
                                                
    public static function success_ban() {
        return trans('users/message.success.ban');
    } 
                                                
    public static function success_unban() {
        return trans('users/message.success.unban');
    } 
                                                
    public static function success_suspend() {
        return trans('users/message.success.suspend');
    } 
                                                
    public static function success_unsuspend() {
        return trans('users/message.success.unsuspend');
    } 
                                                
    public static function success_restored() {
        return trans('users/message.success.restored');
    } 
                                                
    public static function error_create() {
        return trans('users/message.error.create');
    } 
                                                
    public static function error_update() {
        return trans('users/message.error.update');
    } 
                                                
    public static function error_delete() {
        return trans('users/message.error.delete');
    } 
                                                
    public static function error_unsuspend() {
        return trans('users/message.error.unsuspend');
    } 
                                                
    public static function success_created() {
        return trans('users/message.success.created');
    } 
                                                
    public static function success_updated() {
        return trans('users/message.success.updated');
    } 
                                                
    public static function success_deleted() {
        return trans('users/message.success.deleted');
    } 
                                                
    public static function success_banned() {
        return trans('users/message.success.banned');
    } 
                                                
    public static function success_unbanned() {
        return trans('users/message.success.unbanned');
    } 
                                                
    public static function success_suspended() {
        return trans('users/message.success.suspended');
    } 
                                                
    public static function success_unsuspended() {
        return trans('users/message.success.unsuspended');
    } 
                                                
    public static function error_created() {
        return trans('users/message.error.created');
    } 
                                                
    public static function error_updated() {
        return trans('users/message.error.updated');
    } 
                                                
    public static function error_deleted() {
        return trans('users/message.error.deleted');
    } 
                                                
    public static function error_banned() {
        return trans('users/message.error.banned');
    } 
                                                
    public static function error_unbanned() {
        return trans('users/message.error.unbanned');
    } 
                                                
    public static function error_suspended() {
        return trans('users/message.error.suspended');
    } 
                                                
    public static function error_restored() {
        return trans('users/message.error.restored');
    } 
                                                
    public static function welcomeMailPrefix() {
        return trans('users/message.welcome_mail_prefix');
    } 
                                                
    public static function welcomeMailSuffix() {
        return trans('users/message.welcome_mail_suffix');
    } 
                                                
    public static function exists() {
        return trans('message.exists');
    } 
                                                
    public static function notFound() {
        return trans('message._not_found');
    } 
                                                
    public static function nameRequired() {
        return trans('message._name_required');
    } 
                                                
    public static function _success_create() {
        return trans('message.success.create');
    } 
                                                
    public static function _success_update() {
        return trans('message.success.update');
    } 
                                                
    public static function _success_delete() {
        return trans('message.success.delete');
    } 
                                                
    public static function delete_create() {
        return trans('message.delete.create');
    } 
                                                
    public static function delete_update() {
        return trans('message.delete.update');
    } 
                                                
    public static function delete_delete() {
        return trans('message.delete.delete');
    } 
                                                
    public static function error_itemExists() {
        return trans('message.error.item_exists');
    } 
                                                
    public static function _success_created() {
        return trans('message.success.created');
    } 
                                                
    public static function _success_updated() {
        return trans('message.success.updated');
    } 
                                                
    public static function _success_deleted() {
        return trans('message.success.deleted');
    } 
                                                
    public static function _error_created() {
        return trans('message.error.created');
    } 
                                                
    public static function _error_updated() {
        return trans('message.error.updated');
    } 
                                                
    public static function _error_deleted() {
        return trans('message.error.deleted');
    } 
                                                
    public static function error_alreadyExists() {
        return trans('message.error.already_exists');
    } 
                                                
    public static function error_notFound() {
        return trans('message.error.not_found');
    } 
                                                
    public static function error_nameRequired() {
        return trans('message.error.name_required');
    } 
                                
}
