<?php
                
namespace App\Lang\System;
                
use Mbcraft\Laravel\GeneratorUtils;

/**
This class is generated by artisan lang:regenerate_helpers.
Manually editing is strongly discouraged.
*/
                
class LOperations {
                                
    public static function __callStatic($name,$args) {
        $key = GeneratorUtils::getKeyFromMethodName($name,$args);
        
        return "No value found for key : ".$key." .";
    }
   
    public function __call($name,$args) {
    
        $to_eval = "";
        foreach ($args as $k => $arg) {
            $param = $k;
            $$param = $arg;
            $to_eval.= $k.",";
        }
        $to_eval = substr($to_eval,0,strlen($to_eval)-2);
        return eval('return self::'.$name.'('.$to_eval.');');
    }
                
    private static function __values($key,$args) {
        if (count($args)==0) {
            return trans($key);
        } else {
            return trans($key.'.'.$args[0]);
        }
    }
                                
    public static function scan_intro() {
        return trans('system/operations.scan.intro');
    } 
                                                
    public static function enableScan_button() {
        return trans('system/operations.enable_scan.button');
    } 
                                                
    public static function disableScan_button() {
        return trans('system/operations.disable_scan.button');
    } 
                                                
    public static function scan_summary() {
        return trans('system/operations.scan.summary');
    } 
                                                
    public static function scan_type() {
        return trans('system/operations.scan.type');
    } 
                                                
    public static function scan_quantity() {
        return trans('system/operations.scan.quantity');
    } 
                                                
    public static function scan_albums() {
        return trans('system/operations.scan.albums');
    } 
                                                
    public static function scan_spots() {
        return trans('system/operations.scan.spots');
    } 
                                                
    public static function scan_newSongs() {
        return trans('system/operations.scan.new_songs');
    } 
                                                
    public static function scan_songsWithoutMetadata() {
        return trans('system/operations.scan.songs_without_metadata');
    } 
                                                
    public static function scan_encryptedSongs() {
        return trans('system/operations.scan.encrypted_songs');
    } 
                                                
    public static function scan_newSpots() {
        return trans('system/operations.scan.new_spots');
    } 
                                                
    public static function scan_spotsWithoutMetadata() {
        return trans('system/operations.scan.spots_without_metadata');
    } 
                                                
    public static function scan_encryptedSpots() {
        return trans('system/operations.scan.encrypted_spots');
    } 
                                
}
